services:
  # Backend Service (Spring Boot)
  - type: web
    name: ecommerce-backend
    env: java
    buildCommand: cd backend && mvn clean install
    startCommand: cd backend && mvn spring-boot:run
    envVars:
      - key: MONGODB_DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JAVA_VERSION
        value: 20

  # Frontend Service (React - Static Site)
  - type: web
    name: ecommerce-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_BASE_URL
        sync: false
      - key: REACT_APP_BACKEND_URL
        sync: false 