services:
  - type: web
    name: ecommerce-backend
    env: java
    buildCommand: mvn clean install -DskipTests
    startCommand: mvn spring-boot:run
    envVars:
      - key: MONGODB_DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JAVA_VERSION
        value: 20
      - key: PORT
        value: 8080 